import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Goldman } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const GoldmanFont = Goldman({
  weight: '400',
  subsets: ["latin"],
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={GoldmanFont.className}
      >
        {children}
      </body>
    </html>
  );
}
